name: ai4pfas
channels:
- rdkit
- conda-forge
- pytorch
- defaults
dependencies:
- python=3.11
- pip
- numpy
- jupyter
- matplotlib
- scikit-learn
- scipy
- pandas
- seaborn
- rdkit
- ipython
- scipy
- scikit-learn
- pytorch
- autograd
- tensorflow
- pip:
  - gpflow
  - torch-geometric
  - torch==2.3.1+cu118
  - torchvision=0.18.1+cu118
  - tensorflow-probability  
  - openpyxl=3.1  
  - tk=8.6.14   
  - tf-keras=2.17
  - zlib=1.2.13   
  - h5py=3.12.1
  - keras=3.5.0 
  - typing_extensions=4.12 
  - datasets
  - ipywidgets
  
